### ISSUE TITLE
Single file or fragmented?

### ISSUE THREAD

**Issue by ScrimpyCat** [ZURASTA/Food-Data#1]
Currently fragmenting the data, however this approach does bring some potential issues. One of which is the possibility for ambiguity. e.g. In the cuisines file, if two countries share the same city name but when translating may be localised differently in certain locales, it becomes trickier to handle (more care needs to be given to avoid this). Whereas combining all of that into a single file would allow for that to be prevented.

An example of a single file layout could be something like this:

``` toml
[info]
  diets = "../translations/diet-names.toml"

[meat] # https://en.wikipedia.org/wiki/Meat
  [meat.info]
    exclude-diet = ["vegan", "vegetarian", "pescetarian", "raw-vegan", "fruitarian"]
    [meat.info.translations]
      [meat.info.translations.en]
        term = "meat"
      [meat.info.translations.fr]
        term = "viande"

  [meat.pork] # https://en.wikipedia.org/wiki/Pork
    [meat.pork.info]
      ingredient = true
      exclude-diet = ["kosher", "halal"]
      [meat.pork.info.translations]
        [meat.pork.info.translations.en]
          term = "pork"
        [meat.pork.info.translations.fr]
          term = "viande de porc"

[vegetable] # https://en.wikipedia.org/wiki/Vegetable#Terminology (Culinary Vegetable)
  [vegetable.info]
    exclude-diet = ["carnivorous", "ketogenic"]
    [vegetable.info.translations]
      [vegetable.info.translations.en]
        term = "vegetable"
      [vegetable.info.translations.fr]
        term = "légume"

  [vegetable.spring-onion] # https://en.wikipedia.org/wiki/Scallion
    [vegetable.spring-onion.info]
      ingredient = true
      [vegetable.spring-onion.info.translations]
        [vegetable.spring-onion.info.translations.en]
          term = "spring onion"
          [vegetable.spring-onion.info.translations.en.AU]
            term = "shallot"
          [vegetable.spring-onion.info.translations.en.US]
            term = "scallion"
          [vegetable.spring-onion.info.translations.en.CA]
            term = "green onion"
          [vegetable.spring-onion.info.translations.en.GB.WLS]
              term = "gibbon"
        [vegetable.spring-onion.info.translations.fr]
          term = "ciboule"

  [vegetable.tuber] # https://en.wikipedia.org/wiki/Tubers
    [vegetable.tuber.info]
      exclude-diet = ["fruitarian"]
      [vegetable.tuber.info.translations]
        [vegetable.tuber.info.translations.en]
          term = "tuber"

    [vegetable.tuber.potato]
      [vegetable.tuber.potato.info]
        ingredient = true
        [vegetable.tuber.potato.info.translations]
          [vegetable.tuber.potato.info.translations.en]
            term = "potato"
          [vegetable.tuber.potato.info.translations.fr]
            term = "pomme de terre"
```

Another option might be to fragment the data with strict directory structures. The above might look something like:

```
ingredients/
├── meats/
│   ├── __info__.toml #contains: [meat.info]
│   └── pork.toml #contains: [meat.pork.info]
└── vegetables/
    ├── __info__.toml #contains: [vegetable.info]
    ├── spring-onion.toml #contains: [vegetable.spring-onion.info]
    └── tubers/
        ├── __info__.toml #contains: [vegetable.tuber.info]
        └── potato.toml #contains: [vegetable.tuber.potato.info]

or

ingredients/
├── meats/
│   ├── meats.toml #contains: [meat.info]
│   └── pork.toml #contains: [meat.pork.info]
└── vegetables/
    ├── vegetables.toml #contains: [vegetable.info]
    ├── spring-onion.toml #contains: [vegetable.spring-onion.info]
    └── tubers/
        ├── tubers.toml #contains: [vegetable.tuber.info]
        └── potato.toml #contains: [vegetable.tuber.potato.info]

or

ingredients/
├── meats.toml #contains: [meat.info]
├── meats/
│   └── pork.toml #contains: [meat.pork.info]
├── vegetables.toml #contains: [vegetable.info]
└── vegetables/
    ├── spring-onion.toml #contains: [vegetable.spring-onion.info]
    ├── tubers.toml #contains: [vegetable.tuber.info]
    └── tubers/
        └── potato.toml #contains: [vegetable.tuber.potato.info]
```

Benefit of the latter would be it prevents a single file from growing too large (can be broken up), however navigation might be more difficult.
